#!/usr/bin/perl -w

# Run on a shell like:
# psize "Math::BigInt->new(123)"

use strict;
use Devel::Size::Report qw/report_size/;

my $token = shift || '"A scalar"';

my $options = shift || {};
eval (" \$options = { $options }") if !ref $options;

$options->{head} =
 "Size report v$Devel::Size::Report::VERSION for '$token' =>"; 

my $eval = $token;

# make "Foo->new(1)" => "use Foo; Foo->new(1)"
$eval = "use $1; $token" if $token =~ /^\s*([\w:]+)->/;

print report_size ( eval $eval, $options ); 
